# Generated by Django 6.0.2 on 2026-02-14 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('course_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('ELECTIVE', 'Elective'), ('VAM', 'VAM')], default='THEORY', max_length=20)),
                ('min_weekly_lectures', models.PositiveIntegerField()),
                ('max_weekly_lectures', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='assigned_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='strength',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together={('term', 'name')},
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.course'),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'student_group')},
        ),
    ]
