# Generated by Django 6.0.2 on 2026-02-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_course_courseoffering_assigned_faculty_and_more'),
        ('faculty', '0002_alter_facultysubjecteligibility_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
