# Generated by Django 6.0.2 on 2026-03-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_delete_courses'),
        ('faculty', '0003_faculty_is_active_alter_faculty_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab')], default='THEORY', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='program',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='program',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='program',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='program',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='program',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='program',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='course',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_consecutive_slots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_lab_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='weekly_load',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='assigned_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments', to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['program'], name='academics_a_program_fffa7a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='academics_c_code_21c5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type'], name='academics_c_course__e654f0_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['student_group'], name='academics_c_student_f9462d_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['assigned_faculty'], name='academics_c_assigne_4de673_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='academics_d_code_791f98_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['code'], name='academics_p_code_b3fb49_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgroup',
            index=models.Index(fields=['term'], name='academics_s_term_id_cf05a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.UniqueConstraint(fields=('program', 'year', 'semester'), name='unique_term_per_program'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('course', 'student_group'), name='unique_course_per_group'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='unique_program_per_department'),
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.UniqueConstraint(fields=('term', 'name'), name='unique_group_per_term'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='academics_r_room_ty_4036da_idx'),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_versions', to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='workingday',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='academics.program'),
        ),
        migrations.AddIndex(
            model_name='timetableversion',
            index=models.Index(fields=['term'], name='academics_t_term_id_15d207_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetableversion',
            constraint=models.UniqueConstraint(fields=('term', 'version_number'), name='unique_version_per_term'),
        ),
        migrations.AddConstraint(
            model_name='workingday',
            constraint=models.UniqueConstraint(fields=('program', 'day'), name='unique_working_day_per_program'),
        ),
    ]
