# Generated by Django 6.0.2 on 2026-03-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_duplicate_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
