# Generated by Django 6.0.2 on 2026-03-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_add_program_semester_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('ELECTIVE', 'Elective'), ('VAM', 'VAM'), ('SEMINAR', 'Seminar'), ('PROJECT', 'Project'), ('COMPULSORY', 'Compulsory')], default='THEORY', max_length=20),
        ),
    ]
