# Generated by Django 6.0.2 on 2026-03-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_add_course_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('PC', 'Program Core'), ('PE', 'Program Elective'), ('OE', 'Open Elective'), ('BSC', 'Basic Sciences Course'), ('ESC', 'Engineering Sciences Course'), ('HUM', 'Humanities'), ('LS', 'Life Skills'), ('VAM', 'Value Added Module'), ('AEC', 'Ability Enhancement Course'), ('PR', 'Practical (Lab)'), ('PRJ', 'Project'), ('DIS', 'Dissertation'), ('INT', 'Internship'), ('RND', 'Research')], default='PC', max_length=20),
        ),
    ]
