# Generated by Django 6.0.2 on 2026-03-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_migrate_old_course_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_weekly_lectures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='min_weekly_lectures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
