# Generated by Django 6.0.2 on 2026-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_auto_derive_lectures_from_credits'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='program',
            name='unique_program_per_department',
        ),
        migrations.AddField(
            model_name='program',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='program',
            name='total_semesters',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='program',
            name='total_years',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['department'], name='academics_p_departm_fc4bd8_idx'),
        ),
    ]
