# Generated by Django 6.0.2 on 2026-04-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_backfill_course_derived_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='elective_slot_group',
            field=models.CharField(blank=True, db_index=True, help_text='Offerings sharing this value are forced to the same day+slot with different rooms. Used for parallel PE electives.', max_length=50, null=True),
        ),
    ]
