# Generated by Django 6.0.2 on 2026-04-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_courseoffering_elective_slot_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='parent_course_code',
            field=models.CharField(blank=True, help_text='If this is an elective choice, the code of the placeholder course (e.g. PE-I)', max_length=20, null=True),
        ),
    ]
