# Generated by Django 6.0.2 on 2026-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_course_parent_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text='List of working days for this section, e.g. ["MON", "TUE", "WED", "THU", "FRI", "SAT"]'),
        ),
    ]
