# Generated by Django 6.0.2 on 2026-04-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_studentgroup_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='combined_token',
            field=models.CharField(blank=True, help_text='Common token for linked sessions (A+B)', max_length=50, null=True),
        ),
    ]
