# Generated by Django 6.0.2 on 2026-04-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_courseoffering_combined_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='parent_course_code',
            field=models.CharField(blank=True, help_text='If this is an elective choice, the code of the placeholder course (e.g. PE-I)', max_length=50, null=True),
        ),
    ]
