# Generated by Django 6.0.2 on 2026-04-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_expand_course_code_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='short_form',
            field=models.CharField(blank=True, default='', help_text='Short abbreviation e.g. BTCSE, BCAFSD — used for internal suffixes and compact displays', max_length=20),
        ),
    ]
