# Generated by Django 6.0.2 on 2026-02-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_delete_courses'),
        ('faculty', '0003_faculty_is_active_alter_faculty_employee_id_and_more'),
        ('infrastructure', '0002_building_is_active_room_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('slot_number', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_lunch', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('day', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='LectureAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.room')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='scheduler.timetable')),
            ],
            options={
                'unique_together': {('room', 'timeslot', 'timetable')},
            },
        ),
    ]
