# Generated by Django 6.0.2 on 2026-03-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_room_timetableversion_workingday_and_more'),
        ('faculty', '0004_alter_facultysubjecteligibility_unique_together_and_more'),
        ('infrastructure', '0003_alter_programroommapping_unique_together_and_more'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lectureallocation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lectureallocation',
            name='hard_constraint_violated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lectureallocation',
            name='soft_constraint_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='timetable',
            name='total_constraint_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='lectureallocation',
            index=models.Index(fields=['faculty'], name='scheduler_l_faculty_13a888_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureallocation',
            index=models.Index(fields=['room'], name='scheduler_l_room_id_13bf09_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureallocation',
            index=models.Index(fields=['timeslot'], name='scheduler_l_timeslo_1910a4_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureallocation',
            index=models.Index(fields=['timetable'], name='scheduler_l_timetab_b477bf_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['day'], name='scheduler_t_day_d5638f_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['term'], name='scheduler_t_term_id_d35ca8_idx'),
        ),
        migrations.AddConstraint(
            model_name='lectureallocation',
            constraint=models.UniqueConstraint(fields=('timetable', 'room', 'timeslot'), name='unique_room_per_slot_per_timetable'),
        ),
        migrations.AddConstraint(
            model_name='lectureallocation',
            constraint=models.UniqueConstraint(fields=('timetable', 'faculty', 'timeslot'), name='unique_faculty_per_slot_per_timetable'),
        ),
        migrations.AddConstraint(
            model_name='lectureallocation',
            constraint=models.UniqueConstraint(fields=('timetable', 'course_offering', 'timeslot'), name='unique_group_per_slot_per_timetable'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('day', 'slot_number'), name='unique_day_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('term', 'version'), name='unique_timetable_version_per_term'),
        ),
    ]
