# Generated by Django 6.0.2 on 2026-03-18 10:56

import django.db.models.deletion
from django.db import migrations, models


def backfill_student_group(apps, schema_editor):
    LectureAllocation = apps.get_model('scheduler', 'LectureAllocation')
    for allocation in LectureAllocation.objects.select_related('course_offering__student_group').all():
        if allocation.student_group_id is None and allocation.course_offering_id is not None:
            allocation.student_group_id = allocation.course_offering.student_group_id
            allocation.save(update_fields=['student_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_room_timetableversion_workingday_and_more'),
        ('faculty', '0005_alter_teacheravailability_day'),
        ('infrastructure', '0003_alter_programroommapping_unique_together_and_more'),
        ('scheduler', '0002_alter_lectureallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lectureallocation',
            name='unique_group_per_slot_per_timetable',
        ),
        migrations.AddField(
            model_name='lectureallocation',
            name='student_group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_allocations', to='academics.studentgroup'),
        ),
        migrations.RunPython(backfill_student_group, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3),
        ),
        migrations.AddConstraint(
            model_name='lectureallocation',
            constraint=models.UniqueConstraint(fields=('timetable', 'student_group', 'timeslot'), name='unique_group_per_slot_per_timetable'),
        ),
    ]
