# Generated by Django 6.0.2 on 2026-03-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_lectureallocation_unique_group_per_slot_per_timetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025-26', max_length=20)),
                ('max_hours_dean', models.PositiveIntegerField(default=6)),
                ('max_hours_hod', models.PositiveIntegerField(default=12)),
                ('max_hours_senior', models.PositiveIntegerField(default=16)),
                ('max_hours_regular', models.PositiveIntegerField(default=18)),
                ('max_hours_visiting', models.PositiveIntegerField(default=8)),
                ('max_lectures_per_day', models.PositiveIntegerField(default=4)),
                ('max_consecutive_lectures', models.PositiveIntegerField(default=2)),
                ('allow_weekend_classes', models.BooleanField(default=False)),
                ('enforce_room_type', models.BooleanField(default=True)),
                ('enforce_faculty_availability', models.BooleanField(default=True)),
                ('prioritize_senior_faculty', models.BooleanField(default=True)),
                ('auto_publish_timetable', models.BooleanField(default=False)),
                ('notify_on_generation_complete', models.BooleanField(default=True)),
                ('notify_on_failed_generation', models.BooleanField(default=True)),
                ('keep_history_versions', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Scheduler Configuration',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read'], name='scheduler_n_is_read_a908d6_idx')],
            },
        ),
    ]
