# Generated by Django 6.0.2 on 2026-04-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_timeslot_day'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lectureallocation',
            name='unique_group_per_slot_per_timetable',
        ),
    ]
