# Generated by Django 6.0.2 on 2026-04-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_alter_faculty_role'),
        ('scheduler', '0006_remove_group_slot_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureallocation',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
    ]
