# Generated by Django 6.0.2 on 2026-04-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_allow_null_faculty'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lectureallocation',
            name='unique_room_per_slot_per_timetable',
        ),
        migrations.RemoveConstraint(
            model_name='lectureallocation',
            name='unique_faculty_per_slot_per_timetable',
        ),
    ]
