# Generated by Django 6.0.2 on 2026-06-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_remove_lectureallocation_unique_room_per_slot_per_timetable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='draft_base_id',
            field=models.IntegerField(blank=True, help_text='Source timetable ID this draft was cloned from', null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
