# Generated by Django 6.0.2 on 2026-06-12 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_alter_programroommapping_unique_together_and_more'),
        ('scheduler', '0009_add_draft_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureallocation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.room'),
        ),
    ]
