# Generated by Django 6.0.2 on 2026-02-05 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('role', models.CharField(choices=[('DEAN', 'Dean'), ('HOD', 'Head of Department'), ('SENIOR', 'Senior Faculty'), ('REGULAR', 'Regular Faculty'), ('VISITING', 'Visiting Faculty')], max_length=10)),
                ('max_lectures_per_day', models.PositiveIntegerField(default=4)),
                ('max_consecutive_lectures', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='FacultySubjectEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_faculty', to='academics.courses')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_subjects', to='faculty.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'course')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('start_slot', models.PositiveIntegerField()),
                ('end_slot', models.PositiveIntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='faculty.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'day', 'start_slot', 'end_slot')},
            },
        ),
    ]
