# Generated by Django 6.0.2 on 2026-02-14 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_course_courseoffering_assigned_faculty_and_more'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultysubjecteligibility',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_faculty', to='academics.course'),
        ),
    ]
