# Generated by Django 6.0.2 on 2026-02-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_facultysubjecteligibility_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='role',
            field=models.CharField(choices=[('DEAN', 'Dean'), ('HOD', 'Head of Department'), ('SENIOR', 'Senior Faculty'), ('REGULAR', 'Regular Faculty'), ('VISITING', 'Visiting Faculty')], default='REGULAR', max_length=10),
        ),
    ]
