# Generated by Django 6.0.2 on 2026-03-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_room_timetableversion_workingday_and_more'),
        ('faculty', '0003_faculty_is_active_alter_faculty_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultysubjecteligibility',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='faculty',
            name='max_weekly_load',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='facultysubjecteligibility',
            name='priority_weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['employee_id'], name='faculty_fac_employe_5f553f_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['role'], name='faculty_fac_role_f2fff0_idx'),
        ),
        migrations.AddIndex(
            model_name='facultysubjecteligibility',
            index=models.Index(fields=['faculty'], name='faculty_fac_faculty_b2dc35_idx'),
        ),
        migrations.AddIndex(
            model_name='facultysubjecteligibility',
            index=models.Index(fields=['course'], name='faculty_fac_course__166318_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(fields=['faculty'], name='faculty_tea_faculty_288db1_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(fields=['day'], name='faculty_tea_day_a58b73_idx'),
        ),
        migrations.AddConstraint(
            model_name='facultysubjecteligibility',
            constraint=models.UniqueConstraint(fields=('faculty', 'course'), name='unique_faculty_course_pair'),
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.UniqueConstraint(fields=('faculty', 'day', 'start_slot', 'end_slot'), name='unique_availability_block'),
        ),
    ]
