# Generated by Django 6.0.2 on 2026-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_facultysubjecteligibility_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheravailability',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3),
        ),
    ]
