# Generated by Django 6.0.2 on 2026-03-22 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_add_credits_to_course'),
        ('faculty', '0005_alter_teacheravailability_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='academics.department'),
        ),
    ]
