# Generated by Django 5.2.12 on 2026-03-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0006_add_department_to_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="role",
            field=models.CharField(
                choices=[
                    ("PVC", "Pro Vice Chancellor"),
                    ("DEAN", "Dean of School"),
                    ("HOD", "Head of Department"),
                    ("REGULAR", "Regular Faculty"),
                    ("VISITING", "Visiting / Contractual"),
                ],
                default="REGULAR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="facultysubjecteligibility",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="teacheravailability",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
