# Generated by Django 6.0.2 on 2026-04-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_add_department_to_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='role',
            field=models.CharField(choices=[('DEAN', 'Dean'), ('HOD', 'Head of Department'), ('PVC', 'Pro Vice Chancellor'), ('REGULAR', 'Regular Faculty'), ('VISITING', 'Visiting Faculty')], default='REGULAR', max_length=10),
        ),
    ]
