# Generated by Django 6.0.2 on 2026-04-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_add_pvc_remove_senior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='role',
            field=models.CharField(choices=[('PVC', 'Pro Vice Chancellor'), ('DEAN', 'Dean of School'), ('HOD', 'Head of Department'), ('REGULAR', 'Regular Faculty'), ('VISITING', 'Visiting / Contractual')], default='REGULAR', max_length=10),
        ),
    ]
