# Generated by Django 6.0.2 on 2026-04-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_alter_faculty_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='Human-readable title, e.g. Professor, Assistant Professor', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='teaches_lab',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='teaches_theory',
            field=models.BooleanField(default=True),
        ),
    ]
