# Generated by Django 6.0.2 on 2026-04-19 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_add_program_short_form'),
        ('faculty', '0009_add_designation_teaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProgramExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_programs', to='faculty.faculty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_faculty', to='academics.program')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('faculty', 'program'), name='unique_faculty_program_excl')],
            },
        ),
        migrations.CreateModel(
            name='FacultySemesterExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_semesters', to='faculty.faculty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_excluded_faculty', to='academics.program')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('faculty', 'program', 'semester'), name='unique_faculty_sem_excl')],
            },
        ),
    ]
