# Generated by Django 6.0.2 on 2026-03-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_room_timetableversion_workingday_and_more'),
        ('infrastructure', '0002_building_is_active_room_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programroommapping',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='programroommapping',
            name='priority_weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='is_shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='priority_weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['code'], name='infrastruct_code_61c7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['is_active'], name='infrastruct_is_acti_92498d_idx'),
        ),
        migrations.AddIndex(
            model_name='programroommapping',
            index=models.Index(fields=['program'], name='infrastruct_program_f89625_idx'),
        ),
        migrations.AddIndex(
            model_name='programroommapping',
            index=models.Index(fields=['room'], name='infrastruct_room_id_fae305_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='infrastruct_room_ty_e00bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['capacity'], name='infrastruct_capacit_b0571c_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active'], name='infrastruct_is_acti_fc496d_idx'),
        ),
        migrations.AddConstraint(
            model_name='programroommapping',
            constraint=models.UniqueConstraint(fields=('program', 'room'), name='unique_program_room_pair'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'room_number'), name='unique_room_per_building'),
        ),
    ]
